project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Ong Jia Yue adventures in Master of Urban Spatial Analytics"
  page-footer:
    left: "jiaong@upenn.edu"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/JiaYue-Ong
        text: "Ong Jia Yue GitHub"
      - icon: linkedin
        href: www.linkedin.com/in/jia-yue-ong/
        text: "Ong Jia Yue Linkedin"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: analysis/index.qmd
        contents:
          - analysis/shortabstract.qmd
          - analysis/1.1-Get_Data.ipynb
          - analysis/1.2-Exploratory_Plots.ipynb
          - analysis/1.2-Exploratory_Plots_Map.ipynb
          - analysis/1.3-Clustering.ipynb
          - analysis/1.4-PredictiveModelling.ipynb
          - analysis/1.5-Conclusion.ipynb
          - analysis/1.6-Time_Series.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
